# Generated by Django 4.0.4 on 2022-05-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featureimg',
            field=models.ImageField(default='timeline-1.jpg', upload_to='profile_images'),
        ),
    ]
