# Generated by Django 4.0.4 on 2022-06-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
